### DISCUSSION TITLE
Add a closeread in a quarto book on gitlab-pages

### DISCUSSION THREAD

**Discussion by Douxvalkyn** [qmd-lab/closeread#130] [General]
Hello !
How can I add a closeread into an existing quarto **book** on **gitlab-pages** ? 
When I try, the closeread.html page doesn't scroll and therefore doesn't work. Outside the quarto book, my closeread.html is OK.
My _quarto.yml look like this:

```
project:
  type: book
  output-dir: _book

book:
  title: "Etude"
  date: today
  date-format: "DD/MM/YYYY"
  navbar:
    background: primary
  page-navigation: true
  back-to-top-navigation: true
  chapters:
    - index.qmd
    - closeread.qmd
    - part: "A"
      chapters: 
        - quarto/page0.qmd
        - quarto/page1.qmd
        - quarto/page2.qmd
        - quarto/page3.qmd
        - quarto/page4.qmd
    - part: "B"
      chapters:
        - quarto/plan.qmd
        - quarto/text.qmd
        - quarto/figures.qmd
    - quarto/biblio.qmd


format: 
  html:
    page-layout: full 
    theme: cosmo
    css: styles.css
    number-depth: 6
    toc: TRUE
    toc-depth: 6
    toc-title: Sommaire
    date-format: "DD/MM/YYYY"
    echo: true
    code-fold: true 
```

It works beside the quarto book, but not into the quarto book;
this artifact is OK:
public/
public/_extensions
public/closeread_files
public/data
public/quarto
public/closeread.html
public/index.html

**Comment by factorialmap** [comment]
I haven't tried this with book, but with website I changed the `qmd` header and it worked. 

```
---
title: ""
format:
  closeread-html:
    cr-style:
      narrative-background-color-overlay: "#9e948f"
      narrative-text-color-overlay: "#f1e3dd"
      narrative-background-color-sidebar: "#563f46"
      narrative-text-color-sidebar: "#f1e3dd"
---
```
