### ISSUE TITLE
YAML options for colour and other customisations

### ISSUE THREAD

**Issue by jimjam-slam** [qmd-lab/closeread#99]
If the user specifies, for example:

```yaml
---
title: Test
format:
  closeread-html:
    cr-section:
      sidebar-background-color: orangered
      trigger-background-color: darkgrey
      # note the quoting for hex values
      trigger-text-color: "#efefef"
---
```

Propogate these options down to the `style` attribute of all `.cr-sections` (unless those CSS properties are already defined in the style attribute of that section — eg. if the user has tried to customise themselves).

- [ ] Which properties?
  - Sidebar background color
  - Trigger/narrative background color
  - Trigger/narrative text color
  - Trigger/narrative max width
  - Trigger/narrative margin-start or margin-end (for overlay-left and overlay-right respectively)
  - Trigger/narrative border radius?
  - Sticky content font size

- [ ] Add documentation on these options
